"""add thinking_content to messages

Revision ID: 251a05db90b7
Revises: 001_init_all_tables
Create Date: 2026-05-12 08:09:24.872300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251a05db90b7'
down_revision: Union[str, None] = '001_init_all_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thinking_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'thinking_content')
    # ### end Alembic commands ###
